### ISSUE TITLE
When users share their results, a message is pre-populated by default (share screen, P0)

### ISSUE THREAD

**Issue by Juliecat** [johmathe/Starface#5]
tentative copies are

0%: I don't look like any movie star... Too bad!  Download the app StarFace and find out who you look like! (link to app in app store)

1-30%: I kind of look like X. But from very far away...  Download the app StarFace and find out who you look like! (link to app in app store)

31-60%: I look like X. Do you see the resemblance?  Download the app StarFace and find out who you look like! (link to app in app store)

61-80%: I look a lot like X. Do you see the resemblance?  Download the app StarFace and find out who you look like! (link to app in app store)

81-95%: I am X's true doppelgänger. Do you see the resemblance?  Download the app StarFace and find out who you look like! (link to app in app store)

96-100%: You don't fool me. I know this is X. :)  Download the app StarFace and find out who you look like! (link to app in app store)

**Comment by johmathe** [comment]
done
